version: 2.3

jobs:
  build:
    docker:
      - image: circleci/openjdk:11  

    working_directory: ~/repo

    environment:
      DB_PASSWORD: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres

    steps:
      - checkout

     
      - run:
          name: Set execute permission for mvnw
          command: chmod +x mvnw

     
      - run:
          name: Start PostgreSQL Container
          command: |
            docker run -d --name postgres -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -e POSTGRES_DB=$POSTGRES_DB -p 5432:5432 postgres:12.2
          background: false

     
      - run:
          name: Wait for PostgreSQL to Start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m


      - run:
          name: Build Spring Boot Project
          command: ./mvnw clean install  

workflows:
  version: 2
  build:
    jobs:
      - build
