version: 2.1  # Usa la versión adecuada de acuerdo a tus necesidades

jobs:
  build:
    docker:
      - image: circleci/node:14  # La imagen de Docker que deseas usar

    working_directory: ~/repo

    steps:
      - checkout  # Clona el repositorio

      # Agrega pasos aquí para instalar dependencias, ejecutar pruebas, etc.
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - build
