jobs:
  build:
    docker:
      - image: circleci/openjdk:11
      - image: cimg/postgres:15.1
  environment:
    TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test
    auth:
      username: mydockerhub-user
      password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set up PostgreSQL
          command: |
            docker run -d --name mydockerhub-user -e POSTGRES_PASSWORD=$DOCKERHUB_PASSWORD -e POSTGRES_DB=circle_test -p 5432:5432 postgres:15.1
            sleep 5
      - run:
          name: Build with Maven
          command: mvn -B package --file pom.xml
      - run:
          name: Run Spring Boot application
          command: |
            mvn spring-boot:run -Dspring-boot.run.arguments="--spring.datasource.url=jdbc:postgresql://localhost:5432/circle_test,--spring.datasource.user=mydockerhub-user,--spring.datasource.password=$DOCKERHUB_PASSWORD"
      - run:
          name: Test container
          command: |
            which psql
            docker ps
            docker logs postgres
    workflows:
      test_my_app:
        jobs: build-and-deploy
