version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11  # Utiliza la versión de Java que necesites

    working_directory: ~/repo

    environment:
      DB_PASSWORD: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres

    steps:
      - checkout

      # Configura permisos para el archivo mvnw
      - run:
          name: Set execute permission for mvnw
          command: chmod +x mvnw

      # Inicia el contenedor de PostgreSQL
      - run:
          name: Start PostgreSQL Container
          command: |
            docker run -d --name postgres -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -e POSTGRES_DB=$POSTGRES_DB -p 5432:5432 postgres:12.2
          background: true

      # Espera a que el contenedor de PostgreSQL se inicie correctamente
      - run:
          name: Wait for PostgreSQL to Start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Construye el proyecto Spring Boot con Maven
      - run:
          name: Build Spring Boot Project
          command: ./mvnw clean install  # Ajusta este comando según tu proyecto

workflows:
  version: 2
  build:
    jobs:
      - build
