version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11  # Utiliza la versión de Java que necesites

    working_directory: ~/repo

    steps:
      - checkout

      # Construye el proyecto Spring Boot con Maven
      - run:
          name: Build Spring Boot Project
          command: mvnw clean install  # Ajusta este comando según tu proyecto

workflows:
  version: 2
  build:
    jobs:
      - build
