jobs:
  build:
    docker:
      - image: circleci/openjdk:11
      - image: postgres:12.2
    environment:
      DB_PASSWORD: 1234
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set up PostgreSQL
          command: |
            docker run -d --name postgres -e POSTGRES_PASSWORD=1234 -e POSTGRES_DB=postgres -p 5432:5432 postgres:12.2
            sleep 5
      - run:
          name: Build with Maven
          command: mvn -B package --file pom.xml
      - run:
          name: Run Spring Boot application
          command: |
            mvn spring-boot:run -Dspring-boot.run.arguments="--spring.datasource.url=jdbc:postgresql://localhost:5432/mydb,--spring.datasource.user=postgres,--spring.datasource.password=pass"
      - run:
          name: Test container
          command: |
            which psql
            docker ps
            docker logs postgres
    workflows:
      test_my_app:
        jobs: build-and-deploy
