name: Build and Deploy

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up Maven
      uses: actions/setup-maven@v1
      with:
        maven-version: 3.6.3
    - name: Install dependencies
      run: mvn install -DskipTests
    - name: Set up PostgreSQL
      uses: postgres/setup-postgresql@v1
      with:
        version: 12
    - name: Start PostgreSQL
      run: |
        sudo service postgresql start
        psql -c "CREATE DATABASE springboot_app;" -U postgres
    - name: Run Spring Boot application
      run: |
        mvn spring-boot:run -Dspring-boot.run.arguments="--spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_app,--spring.datasource.username=postgres,--spring.datasource.password=postgres"
