name: Build and Deploy

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'openjdk'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
   
    - name: Install dependencies
      run: mvn install -DskipTests
    - name: Set up PostgreSQL
      uses: nnhy/postgresql-action@v1.0
      with:
        version: 12
    - name: Start PostgreSQL
      run: |
        sudo service postgresql start
        psql -c "CREATE DATABASE springboot_app;" -U postgres
    - name: Run Spring Boot application
      run: |
        mvn spring-boot:run -Dspring-boot.run.arguments="--spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_app,--spring.datasource.username=postgres,--spring.datasource.password=postgres"
